<?php declare(strict_types=1);

/*
 * This file is part of phpcov.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
require __DIR__ . '/../../vendor/autoload.php';

use SebastianBergmann\CodeCoverage\Serialization\Serializer;
use SebastianBergmann\CodeCoverage\Serialization\Unserializer;
use SebastianBergmann\CodeCoverage\Util\Filesystem;

$unserializer = new Unserializer;

$world = $unserializer->unserialize(__DIR__ . '/example/coverage/testGreetsWorld.cov');
$name  = $unserializer->unserialize(__DIR__ . '/example/coverage/testGreetsWithName.cov');

// PHPUnit writes the absolute path of the checkout it ran in into each .cov file.
// We store basePath relative to this directory instead and let the .cov file resolve
// it when it is loaded, so that the fixtures work regardless of where the repository
// is checked out.
$write = static function (string $path, array $data): void
{
    if (\dirname($path, 3) !== __DIR__) {
        throw new RuntimeException('Fixture ' . $path . ' is not located in ' . __DIR__ . '/*/coverage');
    }

    if (!\str_starts_with($data['basePath'], __DIR__ . DIRECTORY_SEPARATOR)) {
        throw new RuntimeException('Base path ' . $data['basePath'] . ' is not located in ' . __DIR__);
    }

    $data['basePath'] = \substr($data['basePath'], \strlen(__DIR__ . DIRECTORY_SEPARATOR));

    Filesystem::write(
        $path,
        '<?php // phpunit/php-code-coverage serialization format ' . Serializer::SERIALIZATION_FORMAT . PHP_EOL .
        'return (static function (): array' . PHP_EOL .
        '{' . PHP_EOL .
        "    \$data = \unserialize(<<<'END_OF_COVERAGE_SERIALIZATION'" . PHP_EOL .
        \serialize($data) . PHP_EOL .
        'END_OF_COVERAGE_SERIALIZATION' . PHP_EOL .
        '    );' . PHP_EOL .
        PHP_EOL .
        "    \$data['basePath'] = \dirname(__DIR__, 2) . \DIRECTORY_SEPARATOR . \$data['basePath'];" . PHP_EOL .
        PHP_EOL .
        '    return $data;' . PHP_EOL .
        '})();',
    );
};

// Mismatching driver: testGreetsWorld keeps original, testGreetsWithName gets different driver
$driverName                                                             = $name;
$driverName['buildInformation']['phpCodeCoverage']['driverInformation'] = [
    'name'    => 'PCOV',
    'version' => '1.0.0',
];
$write(__DIR__ . '/mismatching-driver/coverage/testGreetsWorld.cov', $world);
$write(__DIR__ . '/mismatching-driver/coverage/testGreetsWithName.cov', $driverName);

// Mismatching git: both get git info but with different commits
$gitWorld                            = $world;
$gitWorld['buildInformation']['git'] = [
    'originUrl' => 'https://example.com/repo.git',
    'branch'    => 'main',
    'commit'    => 'abc123',
    'status'    => '',
    'isClean'   => true,
];
$gitName                            = $name;
$gitName['buildInformation']['git'] = [
    'originUrl' => 'https://example.com/repo.git',
    'branch'    => 'feature',
    'commit'    => 'def456',
    'status'    => '',
    'isClean'   => true,
];
$write(__DIR__ . '/mismatching-git/coverage/testGreetsWorld.cov', $gitWorld);
$write(__DIR__ . '/mismatching-git/coverage/testGreetsWithName.cov', $gitName);

// Mismatching PHP version: testGreetsWorld keeps original, testGreetsWithName gets different version
$phpName                                           = $name;
$phpName['buildInformation']['runtime']['version'] = '8.4.0';
$write(__DIR__ . '/mismatching-php-version/coverage/testGreetsWorld.cov', $world);
$write(__DIR__ . '/mismatching-php-version/coverage/testGreetsWithName.cov', $phpName);

print 'Generated mismatching fixtures' . PHP_EOL;

// Rewrite the fixtures generated by PHPUnit (rewriting an already processed fixture is a no-op)
foreach (\glob(__DIR__ . '/*/coverage/*.cov') as $path) {
    $write($path, $unserializer->unserialize($path));
}

print 'Made fixtures independent of checkout location' . PHP_EOL;
